### ISSUE TITLE
Patch/Tree window is minimised

### ISSUE THREAD

**Issue by SilkAndSlug** [dracula/gitk#4] opened 2019-11-04 10:31 UTC
The bottom-right window has minimal width, and thus the list of files can't be seen. The window _can_ be resized. The bottom-right window _should_ show, as per [the image on the website](https://draculatheme.com/gitk/).

![Capture](https://user-images.githubusercontent.com/5929297/68114496-0ae59380-feee-11e9-98de-761f9f027c50.PNG)

**Comment by SilkAndSlug** [comment] 2019-11-04 10:58
There appears to be zero documentation for gitk. 

As far as I can see, gitk is writing to ~/.config/git/gitk as it closes, and changing the values of the below params from dracula's defaults. IMHO, gitk is then ignoring the geometry config on load. 

    $ diff ~/gitk/gitk ./gitk
    0a1,18
    > set mainfont {sans 9}
    > set textfont {monospace 9}
    > set uifont {sans 9 bold}
    > set tabstop 8
    > set findmergefiles 0
    > set maxgraphpct 50
    > set maxwidth 16
    > set cmitmode patch
    > set wrapcomment none
    > set autoselect 1
    > set autosellen 40
    > set showneartags 1
    > set maxrefs 20
    > set visiblerefs {"master"}
    > set hideremotes 0
    > set showlocalchanges 1
    > set datetimeformat {%Y-%m-%d %H:%M:%S}
    > set limitdiffs 1
    10a29
    > set diffcontext 3
    13a33,34
    > set extdifftool meld
    > set perfile_attrs 0
    32a54,62
    > set geometry(main) 1200x764+0+0
    > set geometry(state) normal
    > set geometry(topwidth) 1198
    > set geometry(topheight) 495
    > set geometry(pwsash0) "450 1"
    > set geometry(pwsash1) "676 1"
    > set geometry(botwidth) 649
    > set geometry(botheight) 257
    > set permviews {}

I note that, if I delete ~/.config/git/gitk, 
 * gitk starts with the bottom pane divided;
 * the gitk file is regenerated when gitk closes; and
 * setting the botwidth in the file (while gitk is closed) sets the size of the bottom pane(s) when gitk restarts.

Looks like Dracula's config breaks gitk.

**Comment by lourot** [comment] 2019-11-13 16:05
Confirmed: I didn't have any issue before with gitk 2.16.2 on Ubuntu 14.04 but now I have this issue with gitk 2.17.1 on Ubuntu 18.04.

**Comment by lourot** [comment] 2019-11-14 08:57
If you use

```
set want_ttk 1
```

instead of `0` then the problem is gone but suddenly not all the GUI looks dark anymore, and you get some of the problems described [here](https://superuser.com/questions/30175/gitk-looks-ugly-doesnt-honor-theme-settings), so still no quick solution.

**Comment by rmkane** [comment] 2020-05-27 17:40
Having this issue (on Windows 10) also!

@AurelienLourot's solution so enable `want_ttk` shows the patch tree again.

**Comment by lourot** [comment] 2023-06-18 14:32
The issues preventing us from using `set want_ttk 0` have been fixed in
* https://github.com/git/git/pull/1219
* https://github.com/git/git/commit/ef9b086d

The first version containing this fix is `v2.37.0`. On Ubuntu for example it's
available starting from Ubuntu 22.10 (Kinetic):
https://packages.ubuntu.com/kinetic/gitk

I have just tried it out and everything works well now for me.

**Closed as completed** 2023-06-21 08:54 UTC
Labels: bug, help wanted
